server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql-8.0.39/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "+3v0xj1tiqSQmqsR7Vj16/urHtVFyMqSUhHW8WDSCR1VKZ5KDQnCQHa8DlRg7I8X"
  valid-duration: 3600 # in seconds
  refreshable-duration: 360000 # in seconds
